from alexandria.core.apply import try_apply
from alexandria.core.ir import (
    Document,
    Embedding,
    Node,
    Section,
    SectionKind,
    Sentence,
    SentenceId,
    TokenCount,
)
from alexandria.core.protocols import (
    Candidate,
    Delete,
    Embedder,
    Optimizer,
    Params,
    Peers,
    Plan,
    Scorer,
    Scores,
    ScoreVector,
    Selector,
)
from alexandria.core.registry import (
    get_optimizer,
    get_scorer,
    get_selector,
    register_optimizer,
    register_scorer,
    register_selector,
    required_scorers,
    scorer_peers,
)
from alexandria.core.similarity import cosine_distance, cosine_similarity_matrix, normalize

__all__ = [
    "Candidate",
    "Delete",
    "Document",
    "Embedder",
    "Embedding",
    "Node",
    "Optimizer",
    "Params",
    "Peers",
    "Plan",
    "ScoreVector",
    "Scorer",
    "Scores",
    "Section",
    "SectionKind",
    "Selector",
    "Sentence",
    "SentenceId",
    "TokenCount",
    "cosine_distance",
    "cosine_similarity_matrix",
    "get_optimizer",
    "get_scorer",
    "get_selector",
    "normalize",
    "register_optimizer",
    "register_scorer",
    "register_selector",
    "required_scorers",
    "scorer_peers",
    "try_apply",
]
